import { describe, expect, it, vi } from 'vitest'
import { ClaudeConversationAdapter } from '../electron/main/services/conversation/claude-conversation'
import type { ThreadEvent } from '../shared/types/thread'

function fixture() {
  const turns: { args: string[]; data: (chunk: Uint8Array) => void; close: () => void; input: string; writes: unknown[]; ended: boolean }[] = []
  const adapter = new ClaudeConversationAdapter(args => {
    const turn = { args, data: (_chunk: Uint8Array) => {}, close: () => {}, input: '', writes: [] as unknown[], ended: false }
    turns.push(turn)
    return { write: text => { const message = JSON.parse(text); turn.writes.push(message); if (message.type === 'user') turn.input = message.message.content }, endInput: () => { turn.ended = true },
      onData: callback => { turn.data = callback }, onClose: callback => { turn.close = callback }, close: vi.fn(async () => turn.close()) }
  })
  const events: ThreadEvent[] = []
  const emit = (index: number, event: unknown) => turns[index].data(Buffer.from(JSON.stringify(event) + '\n'))
  return { adapter, turns, events, emit }
}

describe('Claude print conversation', () => {
  it('shows native thinking activity from partial messages without exposing thinking text', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('Inspect')
    expect(f.turns[0].args).toContain('--include-partial-messages')
    f.emit(0, { type: 'stream_event', event: { type: 'content_block_start', content_block: { type: 'thinking' } } })
    f.emit(0, { type: 'stream_event', event: { type: 'content_block_delta', delta: { type: 'thinking_delta', thinking: 'private scratch work' } } })
    expect(f.events).toContainEqual(expect.objectContaining({ type: 'activity', phase: 'reasoning' }))
    expect(JSON.stringify(f.events)).not.toContain('private scratch work')
    expect(f.events.some(event => event.type === 'native-signal')).toBe(true)
    await f.adapter.dispose()
  })
  it('shows todo progress only after the corresponding tool succeeds', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('Implement')
    const input = { todos: [{ content: 'Inspect', status: 'completed' }, { content: 'Implement', status: 'in_progress' }] }
    f.emit(0, { type: 'assistant', message: { content: [{ type: 'tool_use', id: 'todos', name: 'TodoWrite', input }] } })
    expect(f.events.some(event => event.type === 'plan')).toBe(false)
    f.emit(0, { type: 'user', message: { content: [{ type: 'tool_result', tool_use_id: 'todos', content: 'Updated' }] } })
    expect(f.events.at(-1)).toMatchObject({ type: 'plan', steps: [{ label: 'Inspect', status: 'completed' }, { label: 'Implement', status: 'inProgress' }] })
    await f.adapter.dispose()
  })
  it('keeps edit inputs distinct from verified disk diffs and records the matching failed result', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('Edit a file')
    f.emit(0, { type: 'assistant', message: { content: [{ type: 'tool_use', id: 'edit', name: 'Edit', input: { file_path: '/project/a.ts', old_string: 'old', new_string: 'new' } }] } })
    expect(f.events.at(-1)).toMatchObject({ files: [{ path: '/project/a.ts', source: 'tool-input', state: 'running' }] })
    f.emit(0, { type: 'user', message: { content: [{ type: 'tool_result', tool_use_id: 'edit', is_error: true, content: 'String not found' }] } })
    expect(f.events.at(-1)).toMatchObject({ state: 'failed', files: [{ source: 'tool-input', state: 'failed' }], output: 'String not found' })
    const last = f.events.at(-1)
    if (last?.type === 'tool') expect(last.files![0].additions).toBeUndefined()
    await f.adapter.dispose()
  })
  it('uses host approvals for workspace access and restarts with the saved session when configuration changes', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: 'saved', model: 'sonnet', reasoningEffort: 'high', access: 'workspace-write' }, event => f.events.push(event))
    await f.adapter.send('Inspect')
    expect(f.turns[0].args).toEqual(expect.arrayContaining(['--permission-prompts', 'host', '--effort', 'high', '--resume', 'saved']))
    f.emit(0, { type: 'control_request', request_id: 'approval', request: { subtype: 'can_use_tool', tool_name: 'Edit', input: { file_path: '/project/a' } } })
    expect(f.events.at(-1)).toMatchObject({ type: 'approval', id: 'approval' })
    await f.adapter.approve('approval', 'decline')
    expect(f.events.at(-1)).toEqual({ type: 'approval-resolved', id: 'approval' })
    f.emit(0, { type: 'result', subtype: 'success', session_id: 'saved' })
    await f.adapter.configure({ model: 'sonnet', reasoningEffort: 'low', access: 'read-only' })
    await f.adapter.send('Continue')
    expect(f.turns[1].args).toEqual(expect.arrayContaining(['--permission-prompts', 'host', '--tools', 'default', '--effort', 'low', '--resume', 'saved']))
    await f.adapter.dispose()
  })
  it('discovers a visual model picker without sending /model as a user prompt or resuming a discovery session', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: 'saved-session' }, event => f.events.push(event))
    const pending = f.adapter.send('/model')
    f.emit(0, { type: 'control_response', response: { request_id: 'commands', subtype: 'success', response: { commands: [], models: [{ value: 'sonnet', displayName: 'Sonnet', description: 'Native model' }], account: { accessToken: 'secret' } } } })
    await pending
    expect(f.turns[0].input).toBe('')
    expect(f.turns[0].args).toContain('--no-session-persistence')
    expect(f.turns[0].args).not.toContain('--resume')
    expect(f.events).toContainEqual(expect.objectContaining({ type: 'model-picker', models: [{ id: 'sonnet', label: 'Sonnet', description: 'Native model', efforts: [], isDefault: false }] }))
    expect(JSON.stringify(f.events)).not.toContain('secret')
    await f.adapter.send('Continue')
    expect(f.turns[1].args).toEqual(expect.arrayContaining(['--resume', 'saved-session']))
    await f.adapter.dispose()
  })
  it('classifies expired OAuth as an operational failure, never assistant knowledge', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('oi')
    f.emit(0, { type: 'assistant', error: 'authentication_failed', message: { id: 'auth', content: [{ type: 'text', text: 'Failed to authenticate: OAuth session expired and could not be refreshed' }] } })
    f.emit(0, { type: 'result', subtype: 'success', is_error: false })
    const outcome = f.events.filter(event => event.type !== 'native-signal')
    expect(outcome).toHaveLength(1)
    expect(outcome[0]).toMatchObject({ type: 'completed', status: 'failed', errorCode: 'authentication' })
    expect(outcome[0]).toMatchObject({ failure: { detail: 'Failed to authenticate: OAuth session expired and could not be refreshed' } })
    await f.adapter.dispose()
  })
  it('retains native command state between turns and explicitly resumes after interruption', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('Investigate auth')
    expect(f.turns[0].input).toBe('Investigate auth')
    expect(f.turns[0].ended).toBe(false)
    expect(f.turns[0].args).toContain('--input-format')
    expect(f.turns[0].args).toContain('default')
    expect(f.turns[0].args).not.toContain('--disable-slash-commands')
    expect(f.turns[0].args).toContain('{"disableAllHooks":true,"disableSkillShellExecution":true}')
    expect(f.turns[0].args).not.toContain('--dangerously-skip-permissions')
    f.emit(0, { type: 'system', subtype: 'init', session_id: 'native-Claude' })
    f.emit(0, { type: 'assistant', message: { id: 'answer', content: [{ type: 'text', text: 'JWT HttpOnly' }, { type: 'thinking', thinking: 'not displayed' }] } })
    f.emit(0, { type: 'result', subtype: 'success', is_error: false })
    expect(f.events).toContainEqual({ type: 'message', id: 'answer', role: 'assistant', text: 'JWT HttpOnly' })
    await f.adapter.send('/model sonnet')
    expect(f.turns).toHaveLength(1)
    expect(f.turns[0].input).toBe('/model sonnet')
    f.emit(0, { type: 'result', subtype: 'success', result: 'Model set to sonnet', is_error: false })
    expect(f.events).toContainEqual(expect.objectContaining({ type: 'message', text: 'Model set to sonnet' }))
    expect(f.events).toContainEqual({ type: 'configuration', model: 'sonnet' })
    await f.adapter.send('/oxe-plan Review auth')
    expect(f.turns[0].input).toBe('/oxe-plan Review auth')
    await f.adapter.interrupt()
    await f.adapter.send('Continue')
    expect(f.turns[1].args).toContain('--resume')
    expect(f.turns[1].args).toContain('native-Claude')
    expect(f.turns[1].args).toEqual(expect.arrayContaining(['--model', 'sonnet']))
    await f.adapter.dispose()
  })
  it('cancellation never becomes success or a subsequent failure', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('Investigate')
    await f.adapter.interrupt()
    f.emit(0, { type: 'result', subtype: 'success' })
    expect(f.events).toEqual([{ type: 'completed', status: 'interrupted' }])
    await f.adapter.dispose()
  })
  it('handles unavailable authentication without persisting provider secrets', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null }, event => f.events.push(event))
    await f.adapter.send('Inspect')
    f.emit(0, { type: 'result', subtype: 'error', is_error: true, result: 'Request failed: api_key=private-secret' })
    const outcome = f.events.find(event => event.type === 'completed')
    expect(outcome).toMatchObject({ type: 'completed', status: 'failed' })
    expect(JSON.stringify(f.events)).not.toContain('private-secret')
    expect(outcome).toMatchObject({ failure: { detail: 'Request failed: api_key=[redacted]' } })
    await expect(f.adapter.approve()).rejects.toThrow('no longer pending')
    await f.adapter.dispose()
  })
  it('answers AskUserQuestion in-process and maps full access to the native bypass mode', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null, access: 'full-access' }, event => f.events.push(event))
    await f.adapter.send('Implement')
    expect(f.turns[0].args).toEqual(expect.arrayContaining(['--permission-mode', 'bypassPermissions', '--permission-prompts', 'host']))
    f.emit(0, { type: 'control_request', request_id: 'question', request: { subtype: 'can_use_tool', tool_name: 'AskUserQuestion', input: { questions: [{ id: 'choice', question: 'Proceed?', options: [{ label: 'Yes' }] }] } } })
    expect(f.events.at(-1)).toMatchObject({ type: 'request', request: { kind: 'question', questions: [{ id: 'choice', question: 'Proceed?' }] } })
    await f.adapter.respondRequest!('question', { answers: { choice: ['Yes'] } })
    expect(f.turns[0].writes.at(-1)).toMatchObject({ type: 'control_response', response: { request_id: 'question', response: { behavior: 'allow', updatedInput: { answers: { choice: 'Yes' } } } } })
    expect(f.events).toContainEqual(expect.objectContaining({ type: 'request-resolved', id: 'question', resolution: 'answered' }))
    f.emit(0, { type: 'control_request', request_id: 'question-2', request: { subtype: 'can_use_tool', tool_name: 'AskUserQuestion', input: { questions: [{ id: 'choice', question: 'Proceed?' }] } } })
    await f.adapter.respondRequest!('question-2', { decision: 'decline' })
    expect(f.events).toContainEqual(expect.objectContaining({ type: 'request-resolved', id: 'question-2', resolution: 'declined' }))
    expect(f.turns[0].writes.at(-1)).toMatchObject({ response: { request_id: 'question-2', response: { behavior: 'deny' } } })
    await f.adapter.dispose()
  })
  it('loads native hooks only after explicit writable configuration', async () => {
    const f = fixture()
    await f.adapter.start({ rootPath: '/project', nativeSessionId: null, access: 'workspace-write', hooksEnabled: true }, event => f.events.push(event))
    await f.adapter.send('Use configured workflow')
    expect(f.turns[0].args).not.toContain('--settings')
    expect(f.turns[0].args).toEqual(expect.arrayContaining(['--permission-mode', 'default', '--permission-prompts', 'host', '--tools', 'default']))
    await f.adapter.dispose()
  })
})
