import { describe, expect, test, vi } from 'vitest'
import { IPC_CHANNELS } from '../../shared/types/ipc'
import { createOxeApi, type PreloadIpc } from '../../electron/preload/api'

describe('preload api', () => {
  test('exposes workspace and terminal APIs without raw ipc access', async () => {
    const ipc = createFakeIpc()
    const api = createOxeApi(ipc)

    await api.workspace.list()
    await api.workspace.create({ rootPath: 'C:/repo', layout: '1x1' })
    await api.workspace.pickFolder()
    await api.workspace.updatePaneType({ paneId: 'pane-1', type: 'editor' })
    await api.workspace.updateEditorState({ workspaceId: 'workspace-1', editorVisible: true, editorWidthPercent: 40 })
    await api.workspace.updateReviewState({ workspaceId: 'workspace-1', reviewPanelVisible: true, reviewPanelWidthPercent: 36 })
    await api.workspace.updateSettings({ workspaceId: 'workspace-1', themeId: 'nord', layoutPreset: 6 })
    await api.terminal.write({ paneId: 'pane-1', data: 'pwd\r' })
    await api.tasks.list('workspace-1')
    await api.tasks.create({ workspaceId: 'workspace-1', title: 'Task' })
    await api.fs.listTree({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.fs.readFile({ workspaceId: 'workspace-1', rootPath: 'C:/repo', relativePath: 'README.md' })
    await api.fs.writeFile({ workspaceId: 'workspace-1', rootPath: 'C:/repo', relativePath: 'README.md', content: 'ok' })
    await api.fs.watchFile({ workspaceId: 'workspace-1', rootPath: 'C:/repo', relativePath: 'README.md' })
    await api.fs.unwatchFile({ watchId: 'watch-1' })
    await api.git.getBranch({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })

    await api.github.getCliStatus({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.getWorkspaceStatus({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.fetch({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.pullFfOnly({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.stageAll({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.stageFile({ workspaceId: 'workspace-1', rootPath: 'C:/repo', path: 'src/a.ts' })
    await api.github.unstageFile({ workspaceId: 'workspace-1', rootPath: 'C:/repo', path: 'src/a.ts' })
    await api.github.commit({ workspaceId: 'workspace-1', rootPath: 'C:/repo', message: 'init' })
    await api.github.generateCommitMessage({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.push({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.commitAndPush({ workspaceId: 'workspace-1', rootPath: 'C:/repo', message: 'init' })
    await api.github.listBranches({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.createBranch({ workspaceId: 'workspace-1', rootPath: 'C:/repo', name: 'feat/x' })
    await api.github.checkoutBranch({ workspaceId: 'workspace-1', rootPath: 'C:/repo', name: 'main' })
    await api.github.listPullRequests({ workspaceId: 'workspace-1', rootPath: 'C:/repo', state: 'open' })
    await api.github.createPullRequest({ workspaceId: 'workspace-1', rootPath: 'C:/repo', title: 'PR', body: '' })
    await api.github.listCommits({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.getCommitDetails({ workspaceId: 'workspace-1', rootPath: 'C:/repo', oid: 'abc123' })
    await api.github.listReleases({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.createRelease({ workspaceId: 'workspace-1', rootPath: 'C:/repo', tagName: 'v1.0.0' })
    await api.github.listWorkflows({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.listWorkflowRuns({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.getWorkflowRunDetails({ rootPath: 'C:/repo', runId: 123 })
    await api.github.runWorkflow({ workspaceId: 'workspace-1', rootPath: 'C:/repo', workflowId: 'wf-1' })
    await api.github.listCheckpoints({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.createCheckpoint({ workspaceId: 'workspace-1', rootPath: 'C:/repo', name: 'snap-1' })
    await api.github.restoreCheckpoint({ workspaceId: 'workspace-1', rootPath: 'C:/repo', checkpointId: 'cp-1' })
    await api.github.deleteCheckpoint({ checkpointId: 'cp-1' })
    await api.github.listConnectedRepositories({ workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    await api.github.connectRepository({ workspaceId: 'workspace-1', rootPath: 'C:/repo', fullName: 'org/repo' })

    expect(api).not.toHaveProperty('ipcRenderer')
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.list)
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.create, { rootPath: 'C:/repo', layout: '1x1' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.pickFolder)
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.updatePaneType, { paneId: 'pane-1', type: 'editor' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.updateEditorState, { workspaceId: 'workspace-1', editorVisible: true, editorWidthPercent: 40 })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.updateReviewState, { workspaceId: 'workspace-1', reviewPanelVisible: true, reviewPanelWidthPercent: 36 })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.workspace.updateSettings, { workspaceId: 'workspace-1', themeId: 'nord', layoutPreset: 6 })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.terminal.write, { paneId: 'pane-1', data: 'pwd\r' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.tasks.list, 'workspace-1')
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.tasks.create, { workspaceId: 'workspace-1', title: 'Task' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.fs.listTree, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.fs.readFile, { workspaceId: 'workspace-1', rootPath: 'C:/repo', relativePath: 'README.md' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.fs.writeFile, {
      workspaceId: 'workspace-1',
      rootPath: 'C:/repo',
      relativePath: 'README.md',
      content: 'ok'
    })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.fs.watchFile, { workspaceId: 'workspace-1', rootPath: 'C:/repo', relativePath: 'README.md' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.fs.unwatchFile, { watchId: 'watch-1' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.git.getBranch, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.getCliStatus, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.getWorkspaceStatus, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.fetch, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.pullFfOnly, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.stageAll, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.stageFile, { workspaceId: 'workspace-1', rootPath: 'C:/repo', path: 'src/a.ts' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.unstageFile, { workspaceId: 'workspace-1', rootPath: 'C:/repo', path: 'src/a.ts' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.commit, { workspaceId: 'workspace-1', rootPath: 'C:/repo', message: 'init' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.generateCommitMessage, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.push, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.commitAndPush, { workspaceId: 'workspace-1', rootPath: 'C:/repo', message: 'init' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listBranches, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.createBranch, { workspaceId: 'workspace-1', rootPath: 'C:/repo', name: 'feat/x' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.checkoutBranch, { workspaceId: 'workspace-1', rootPath: 'C:/repo', name: 'main' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listPullRequests, { workspaceId: 'workspace-1', rootPath: 'C:/repo', state: 'open' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.createPullRequest, { workspaceId: 'workspace-1', rootPath: 'C:/repo', title: 'PR', body: '' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listCommits, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.getCommitDetails, { workspaceId: 'workspace-1', rootPath: 'C:/repo', oid: 'abc123' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listReleases, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.createRelease, { workspaceId: 'workspace-1', rootPath: 'C:/repo', tagName: 'v1.0.0' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listWorkflows, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listWorkflowRuns, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.getWorkflowRunDetails, { rootPath: 'C:/repo', runId: 123 })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.runWorkflow, { workspaceId: 'workspace-1', rootPath: 'C:/repo', workflowId: 'wf-1' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listCheckpoints, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.createCheckpoint, { workspaceId: 'workspace-1', rootPath: 'C:/repo', name: 'snap-1' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.restoreCheckpoint, { workspaceId: 'workspace-1', rootPath: 'C:/repo', checkpointId: 'cp-1' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.deleteCheckpoint, { checkpointId: 'cp-1' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.listConnectedRepositories, { workspaceId: 'workspace-1', rootPath: 'C:/repo' })
    expect(ipc.invoke).toHaveBeenCalledWith(IPC_CHANNELS.github.connectRepository, { workspaceId: 'workspace-1', rootPath: 'C:/repo', fullName: 'org/repo' })
  })

  test('returns unsubscribe functions for terminal and task listeners', () => {
    const ipc = createFakeIpc()
    const api = createOxeApi(ipc)
    const unsubscribe = api.terminal.onData('pane-1', () => undefined)
    const unsubscribeTask = api.tasks.onVerifyOutput(() => undefined)
    const unsubscribeFs = api.fs.onFileChanged(() => undefined)

    unsubscribe()
    unsubscribeTask()
    unsubscribeFs()

    expect(ipc.on).toHaveBeenCalledWith(IPC_CHANNELS.terminal.onData, expect.any(Function))
    expect(ipc.removeListener).toHaveBeenCalledWith(IPC_CHANNELS.terminal.onData, expect.any(Function))
    expect(ipc.on).toHaveBeenCalledWith(IPC_CHANNELS.tasks.onVerifyOutput, expect.any(Function))
    expect(ipc.removeListener).toHaveBeenCalledWith(IPC_CHANNELS.tasks.onVerifyOutput, expect.any(Function))
    expect(ipc.on).toHaveBeenCalledWith(IPC_CHANNELS.fs.onFileChanged, expect.any(Function))
    expect(ipc.removeListener).toHaveBeenCalledWith(IPC_CHANNELS.fs.onFileChanged, expect.any(Function))
  })

  test('shares one IPC subscription while routing terminal events by pane', () => {
    const ipc = createFakeIpc()
    const api = createOxeApi(ipc)
    const first = vi.fn()
    const second = vi.fn()
    const unsubscribeFirst = api.terminal.onData('pane-1', first)
    const unsubscribeSecond = api.terminal.onData('pane-2', second)

    expect(ipc.on).toHaveBeenCalledTimes(1)
    const listener = vi.mocked(ipc.on).mock.calls[0][1]
    listener({} as never, { paneId: 'pane-2', data: 'only second' })

    expect(first).not.toHaveBeenCalled()
    expect(second).toHaveBeenCalledWith({ paneId: 'pane-2', data: 'only second' })
    unsubscribeFirst()
    expect(ipc.removeListener).not.toHaveBeenCalled()
    unsubscribeSecond()
    expect(ipc.removeListener).toHaveBeenCalledTimes(1)
  })
})

function createFakeIpc(): PreloadIpc {
  return {
    invoke: vi.fn().mockResolvedValue(undefined),
    on: vi.fn(),
    removeListener: vi.fn()
  }
}
